### PR TITLE
Fix textstyle memleak

### PR DESCRIPTION
**Pull request by medranocalvo**
* Reduce duplication
* Free TextLayout memory

### CODE REVIEW

**Comment by medranocalvo** [comment]
Thank you.

**Comment by wjoye** [comment]
And thank you for the pull requests. Keep them coming. Nice to have a second pair of eyes on the code.

**Comment by medranocalvo** [comment]
By the way, now that I have your attention: I think there's work ongoing to integrate RBC (Refactored BLT components) into Tk (see https://core.tcl.tk/tips/doc/trunk/tip/510.md and tcl-core).  Have you considered proposing or pointing out this work?

**Comment by wjoye** [comment]
Thanks for the note. At the time, I had looked at RBC before going alone with tkblt. I needed tcl/tk 8.6 compatibility (scalable fonts and rotated text), TEA support and Windows support, and fast. If you want to push tkblt as an alternative, I would support it. Most likely they will not like the C++ code, and would want it downgraded.

**Pull request merged**
